### ISSUE TITLE
authentication 

### ISSUE THREAD

**Issue by dzzirima** [dzzirima/myCert#10]
plz provide  error messages if the user fails to login just as above

@MthandazoJoeJunior 
![error_trunk](https://user-images.githubusercontent.com/52695278/123163251-cb2c4080-d471-11eb-976e-be83b2a10c45.PNG)

**Comment by dzzirima** [comment]
hahaha   am just testing on to raise issues

**Comment by MthandazoJoeJunior** [comment]
Ok kul ankela,

This is definitely not the email I usually use kkkkkk, how did you get it

**Comment by MthandazoJoeJunior** [comment]
Kkk ok ok kul, where is the login code?

**Comment by dzzirima** [comment]
you created your github account with it

**Comment by dzzirima** [comment]
resolved thanks jj ,  i will add to the code base
